### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by abelsiqueira**
This documentation uses Documenter.jl.
To publish you need to first do the steps [here](https://juliadocs.github.io/Documenter.jl/latest/man/hosting.html). More specifically, create a ssh key to store in github and then commit the encripted key. Also, the documentation is only created if a specific branch is pushed (currently develop) or in a tag.

The current documentation was pushed [here](http://abelsiqueira.github.io/NLPModels.jl/latest/).

Summarizing:
- Accept this
- Create ssh key and commit the encripted key (verify the [instructions](https://juliadocs.github.io/Documenter.jl/latest))
- Push to develop

If you give me admin access to this repository, I can do it from here.

### CODE REVIEW

**Comment by dpo** [comment]
Many thanks for this!!!

Is MathJax supported? If so I think it would help to write the problem in math form and refer to the objective and constraints in the documentation.

**Comment by abelsiqueira** [comment]
Updated the docs with the suggestion.

**Comment by dpo** [comment]
Thanks! Will we need to push updated doc manually every time or can Travis do it?

**Comment by abelsiqueira** [comment]
In theory, after correcting the .documenter.enc and the keys on travis and github it should deploy for the develop branch as the latest doc and for the releases also. I don't remember now about the stable docs. Maybe it's the master, maybe it's' the latest release.

**Comment by dpo** [comment]
I gave you admin access. Many thanks for this!

**Comment by abelsiqueira** [comment]
Dropping this because of #25

**Pull request closed without merging**
