### PR TITLE
Prepare for 0.6 - alpha is out

### PR DESCRIPTION
**Pull request by abelsiqueira**

### CODE REVIEW

**Comment by dpo** [comment]
There [an error](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/207291699#L3518) and some warnings.

**Comment by abelsiqueira** [comment]
Yes, that's almost corrected. I'm updating LinearOperators before.

**Comment by abelsiqueira** [comment]
There was some error on Mac 0.6 about not being able to precompile BinDeps. I restarted and it went away.

**Comment by dpo** [comment]
Thank you!

**Pull request merged**
