### PR TITLE
Remove MathProgBase and JuMP

### PR DESCRIPTION
**Pull request by abelsiqueira**
This removes MathProgBase and JuMP to an external package, and adds `ForwardDiff` as a mandatory reference.
- This allows `__precompile__()`
- This allows updating to 0.7

### CODE REVIEW

**Comment by dpo** [comment]
Looks great. Thank you!

**Comment by abelsiqueira** [comment]
Now passing on appveyor. After this I'll release 0.5.0 for `NLPJuMPModels`.

**Comment by dpo** [comment]
Thank you!

**Comment by dpo** [comment]
I suggest to set up CI on NLPJuMPModels before making a release.

**Pull request merged**
