### PR TITLE
Add Pkg.add on documentation

### LINKED ISSUE #49: Missing Pkg.checkout on page

### PR DESCRIPTION
**Pull request by abelsiqueira**
Closes #49

### CODE REVIEW

**Comment by dpo** [comment]
In fact, if we merge develop into master, we don't need to do this, do we?

**Comment by abelsiqueira** [comment]
No. Also, when releasing, it would change to `add` only.

**Comment by dpo** [comment]
Should that information be in the README instead of the docs?

**Comment by abelsiqueira** [comment]
I think it should be on both.

**Comment by dpo** [comment]
Ok. do you want to update this PR so it says `add` and also update the README in prevision of a release?

**Comment by abelsiqueira** [comment]
Yes, I'll do that

**Comment by abelsiqueira** [comment]
Updated. Included some things on the docs that were on the README.

**Comment by dpo** [comment]
👍 Let me know if this is ready.

**Comment by abelsiqueira** [comment]
Ready

**Pull request merged**
