### PR TITLE
When pr is nothing, don't try to create comment on test-breakage

### PR DESCRIPTION
**Pull request by abelsiqueira**

### CODE REVIEW

**Comment by dpo** [comment]
How can `pr` be `nothing`? If Travis is just running the periodic tests on `master`?

**Comment by abelsiqueira** [comment]
I'm not sure it's possible, but the error message here https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/590023532#L6996 is strange, so I'm testing if it's related to `pr` being `nothing`.
If this fail, I'll have to debug in the branch `fix-docs`.

**Comment by abelsiqueira** [comment]
:robot: Testing breakage of this commit

| Package Name | master | Tagged |
|--|--|--|
| AmplNLReader |  |  |
| CaNNOLeS |  |  |
| CUTEst |  |  |
| QuadraticModels |  |  |
| NLPModelsIpopt |  |  |
| NLPModelsJuMP |  |  |
| SolverTools |  |  |

**Comment by abelsiqueira** [comment]
Fixed somewhere else.

**Pull request closed without merging**
