### PR TITLE
Fix check-dimensions tests: constrained hprod! was not called

### PR DESCRIPTION
**Pull request by abelsiqueira**

### CODE REVIEW

**Comment by amontoison** [comment]
https://github.com/JuliaSmoothOptimizers/NLPModels.jl/blob/master/test/problems/lincon.jl#L87
`y`, `v` and `Hv` are missing.

**Comment by abelsiqueira** [comment]
Thanks

**Comment by abelsiqueira** [comment]
:robot: Testing breakage of this pull request

| Package Name | master | stable |
|--|--|--|
| AmplNLReader | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/681776644) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/681776645) | 
| CUTEst | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/681776646) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/681776647) | 
| CaNNOLeS | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/681776648) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/681776649) | 
| NLPModelsIpopt | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/681776650) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/681776651) | 
| NLPModelsJuMP | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/681776652) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/681776653) | 
| QuadraticModels | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/681776654) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/681776655) | 
| SolverTools | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/681776656) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/681776657) |

**Comment by abelsiqueira** [comment]
:robot: Testing breakage of this pull request

| Package Name | master | stable |
|--|--|--|
| AmplNLReader | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/681779806) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/681779807) | 
| CUTEst | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/681779808) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/681779809) | 
| CaNNOLeS | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/681779810) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/681779811) | 
| NLPModelsIpopt | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/681779812) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/681779813) | 
| NLPModelsJuMP | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/681779814) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/681779815) | 
| QuadraticModels | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/681779816) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/681779817) | 
| SolverTools | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/681779818) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/681779819) |

**Comment by dpo** [comment]
Thsnk you.

**Pull request merged**
