### PR TITLE
Drop Julia 1.1 from CI

### PR DESCRIPTION
**Pull request by abelsiqueira**

### CODE REVIEW

**Comment by dpo** [comment]
We could drop them everywhere but then we should also update the Project.toml.

**Comment by abelsiqueira** [comment]
Sure.

**Comment by abelsiqueira** [comment]
I also updated version to 0.12.0 so it can be release right after this.

**Comment by amontoison** [comment]
Maybe we should drop julia 1.2 too? Julia 1.4 will be available soon. (version rc2 currently)
Besides Artifacts (.jll) and the 5 arguments mul! that we want to use with Dominique for LinearOperators.jl / Krylov.jl in the future is only available for Julia >= 1.3.

**Comment by abelsiqueira** [comment]
Now I dropped Julia up to 1.2 and added 1.4. I left version 0.12.0 to after #257.

**Pull request merged**
