### PR TITLE
Define constraint in simple_model test

### PR DESCRIPTION
**Pull request by dpo**
The previous test did not define any constraint.

### CODE REVIEW

**Comment by abelsiqueira** [comment]
Nice catch, thanks. But I just found out that I don't have write access to this repository.

**Comment by dpo** [comment]
I'm not sure why TravisCI isn't kicking in.

**Comment by abelsiqueira** [comment]
The osx release had a [strange error downloading brew](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/147549746#L154). I tried restarting but it said I couldn't.

**Comment by dpo** [comment]
Clearly a Travis  bug. Let's pull this since the other three checked out.

**Pull request merged**
