### PR TITLE
phase out Julia 0.6

### PR DESCRIPTION
**Pull request by dpo**
suppress many (not all) Julia 0.7 warnings

### CODE REVIEW

**Comment by dpo** [comment]
Not so sure where the remaining warnings come from.

**Comment by dpo** [comment]
Julia 1.0 says
```
ERROR: LoadError: too many parameters for type
```
Not sure I understand what the error is.
https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/431711229#L276

**Comment by abelsiqueira** [comment]
I think it's related to the new LinearOperators. I'll try to update this now. May need to update FastClosures too.

**Comment by dpo** [comment]
NLPModels will also need to depend on FastClosures to create `hess_op` and `jac_op`.

**Comment by abelsiqueira** [comment]
Rebased #134 here.

**Comment by dpo** [comment]
It even passes on nightly!

**Pull request merged**
