### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by abelsiqueira**
Tested inside the organization, and now with badges.

http://juliasmoothoptimizers.github.io/NLPModels.jl/latest/

### CODE REVIEW

**Comment by dpo** [comment]
💯

**Comment by dpo** [comment]
I'm thinking that the docs could specify clearly our convention about signs in the Lagrangian.

**Comment by abelsiqueira** [comment]
Convention added

**Comment by abelsiqueira** [comment]
@dpo, the fail here is only on Coverage.
Also, this introduced a change on SimpleNLPModel that I'm using on the tests on TRON.

**Comment by dpo** [comment]
Is this ready to go?

**Comment by abelsiqueira** [comment]
Yes

sent from cell

**Pull request merged**
