### PR TITLE
use strict=true in docs

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by tmigot** [comment]
This fails because of #409 as ADNLPModels has not reached up-to-date NLPModels release.

**Comment by tmigot** [comment]
So, the error comes from duplicate documentation.

The `autodocs` block in the references page print all the docstrings. However, in pages like:
https://juliasmoothoptimizers.github.io/NLPModels.jl/dev/models/
https://juliasmoothoptimizers.github.io/NLPModels.jl/dev/tools/
https://juliasmoothoptimizers.github.io/NLPModels.jl/dev/api/
https://juliasmoothoptimizers.github.io/NLPModels.jl/dev/internals/
we also call some docstring.

I see two solutions:
- we remove the docstrings from this page.
- we replace the docstrings by links to the reference page.

@dpo @abelsiqueira Any idea or opinion?

**Comment by dpo** [comment]
> we replace the docstrings by links to the reference page.

**Comment by tmigot** [comment]
https://juliasmoothoptimizers.github.io/NLPModels.jl/previews/PR411/

**Pull request merged**
