### PR TITLE
Fix docs

### PR DESCRIPTION
**Pull request by abelsiqueira**

### CODE REVIEW

**Comment by abelsiqueira** [comment]
This is actually a placeholder for the next pull request after #209 and #210.
#209 is ready to review and #210 will be rebased and fixed after that. I'll remove the extra functions from #210.

**Comment by abelsiqueira** [comment]
:robot: Testing breakage of this commit

| Package Name | master | Tagged |
|--|--|--|
| AmplNLReader |  |  |
| CaNNOLeS |  |  |
| CUTEst |  |  |
| QuadraticModels |  |  |
| NLPModelsIpopt |  |  |
| NLPModelsJuMP |  |  |
| SolverTools |  |  |

**Comment by abelsiqueira** [comment]
:robot: Testing breakage of this commit

| Package Name | master | Tagged |
|--|--|--|
| QuadraticModels |  |  |
| SolverTools |  |  |

**Comment by abelsiqueira** [comment]
:robot: Testing breakage of this commit

| Package Name | master | Tagged |
|--|--|--|
| AmplNLReader |  |  |
| CaNNOLeS |  |  |
| CUTEst |  |  |
| QuadraticModels |  |  |
| NLPModelsIpopt |  |  |
| NLPModelsJuMP |  |  |
| SolverTools |  |  |

**Comment by abelsiqueira** [comment]
:robot: Testing breakage of this commit

| Package Name | master | Tagged |
|--|--|--|
| AmplNLReader |  |  |
| CaNNOLeS |  |  |
| CUTEst |  |  |
| QuadraticModels |  |  |
| NLPModelsIpopt |  |  |
| NLPModelsJuMP |  |  |
| SolverTools |  |  |

**Comment by abelsiqueira** [comment]
I've merged this since it passes on Travis and it is simply correcting the docstrings.

**Comment by dpo** [comment]
Sounds good, thanks.

**Pull request merged**
