### PR TITLE
Remove SimpleModel

### PR DESCRIPTION
**Pull request by abelsiqueira**
Just deletions

### CODE REVIEW

**Comment by dpo** [comment]
Should this go to a separate repo SimpleNLPModels.jl?

**Comment by abelsiqueira** [comment]
I think now for two reasons:
- I rather not maintain it;
- It's a very thin layer on top of just writing a specific model, such as `BROWNDEN <: AbstractNLPModel` and defining all api function for `nlp :: BROWNDEN`. The next PR shall introduce the problems in this format.

**Comment by dpo** [comment]
I agree with you. Could the docs show a simple example? Perhaps they already do?!

**Comment by abelsiqueira** [comment]
They news docs should, I'll add to my list, in case I forgot.

**Pull request merged**
