### PR TITLE
Fix types in slack model (fix #217)

### LINKED ISSUE #214: ADModels: better prods
Instead of having
```
hessian(nlp, x) * v
```
we could have
```
derivative(t -> gradient(nlp, x + t * v))
```

### LINKED ISSUE #217: SlackModel loses type of x
When creating `NLPModelMeta`.

### PR DESCRIPTION
**Pull request by abelsiqueira**
Closes #217

### CODE REVIEW

**Comment by abelsiqueira** [comment]
:robot: Testing breakage of this commit

| Package Name | master | Tagged |
|--|--|--|
| AmplNLReader |  |  |
| CaNNOLeS |  |  |
| CUTEst |  |  |
| QuadraticModels |  |  |
| NLPModelsIpopt |  |  |
| NLPModelsJuMP |  |  |
| SolverTools |  |  |

**Comment by dpo** [comment]
Seems like some wrong versions are being picked up by `breakage`. For instance, AmplNLReader 0.6 is only for julia 1.3.

**Comment by abelsiqueira** [comment]
The way I implemented it, it tests whether the latest released version works. I think it's better to update the version in `test-breakage`.

**Comment by abelsiqueira** [comment]
:robot: Testing breakage of this commit

| Package Name | master | Tagged |
|--|--|--|
| AmplNLReader |  |  |
| CaNNOLeS |  |  |
| CUTEst |  |  |
| QuadraticModels |  |  |
| NLPModelsIpopt |  |  |
| NLPModelsJuMP |  |  |
| SolverTools |  |  |

**Comment by dpo** [comment]
* SolverTools fails with "Error: status bad is not a valid status."
* NLPModelsJuMP fails with "Pkg.Types.PkgError("empty intersection between NLPModels@0.10.0 and project compatibility 0.9")"
* CUTEst and CaNNOLeS fail due to a version issue with LinearOperators

**Comment by abelsiqueira** [comment]
> SolverTools fails with "Error: status bad is not a valid status." Not sure how it indicates that the tests pass (travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/622705945#L2300)

This is actually a `@test_throws` in SolverTools, so it's actually working.

**Comment by abelsiqueira** [comment]
NLPModelsJuMP fails because it doesn't support NLPModels 0.10.

**Comment by dpo** [comment]
How come it doesn't install a compatible version when you run `Pkg.add()`?

**Comment by abelsiqueira** [comment]
The PR version of `NLPModels` is being tested, it is fixed. So when it tries to install `NLPModelsJuMP`, for instance, it doesn't really work.

The breakage system only works for checking whether a PR breaks support. But without continuous support, it breaks more often than not. What can we improve this?

**Comment by abelsiqueira** [comment]
I'm gonna release NLPModelsJuMP 0.4.1, update it to work with NLPModels 0.10.0, and release NLPModelsJuMP 0.5.0. I imagine CUTEst has something similar, and I started the same for CaNNOLeS yesterday.

**Comment by abelsiqueira** [comment]
:robot: Testing breakage of this commit

| Package Name | master | Tagged |
|--|--|--|
| AmplNLReader |  |  |
| CaNNOLeS |  |  |
| CUTEst |  |  |
| QuadraticModels |  |  |
| NLPModelsIpopt |  |  |
| NLPModelsJuMP |  |  |
| SolverTools |  |  |

**Comment by dpo** [comment]
There's an error in test_breakage related to adding a comment to this PR: https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/637606573#L3121.

Also we should allow failure for nightly on FreeBSD.

**Comment by abelsiqueira** [comment]
For some reason, it worked 6 hours ago, and now it failed again...

I was trying to recreate it here: https://github.com/abelsiqueira/NLPModels.jl/pull/4

**Comment by dpo** [comment]
I restarted it. Let's see what happens.

**Comment by abelsiqueira** [comment]
:robot: Testing breakage of this commit

| Package Name | master | Tagged |
|--|--|--|
| AmplNLReader |  |  |
| CaNNOLeS |  |  |
| CUTEst |  |  |
| QuadraticModels |  |  |
| NLPModelsIpopt |  |  |
| NLPModelsJuMP |  |  |
| SolverTools |  |  |

**Comment by abelsiqueira** [comment]
Finally worked, and all tagged versions passed too.

**Pull request merged**
