### PR TITLE
Remove jth_hess_residual, hess and jac implementations for test models

### PR DESCRIPTION
**Pull request by amontoison**
I didn't remove `hess` for browden model because it was used for `hess_coord!` and `hprod!`.

### CODE REVIEW

**Comment by amontoison** [comment]
Cirrus and auto-merge are not run again if we close / reopen pull request for information.

**Comment by dpo** [comment]
You would have to rebase for auto-merge, no?

**Comment by amontoison** [comment]
-> minimumApprovals: There are not enough approvals by reviewers

**Comment by abelsiqueira** [comment]
Let's see if anything changes in the next PR. According to the settings, we are both owners.

**Comment by abelsiqueira** [comment]
Thanks

**Pull request merged**
