### PR TITLE
Remove rows and cols from coord functions

### LINKED ISSUE #192: Remove `rows` and `cols` for coord functions
Since `coord` functions can't touch `rows` and `cols`, we should remove these arguments.

### PR DESCRIPTION
**Pull request by abelsiqueira**
Blocked by #215, do not merge.

Closes #192

### CODE REVIEW

**Comment by abelsiqueira** [comment]
:robot: Testing breakage of this commit

| Package Name | master | Tagged |
|--|--|--|
| AmplNLReader |  |  |
| CaNNOLeS |  |  |
| CUTEst |  |  |
| QuadraticModels |  |  |
| NLPModelsIpopt |  |  |
| NLPModelsJuMP |  |  |
| SolverTools |  |  |

**Comment by abelsiqueira** [comment]
:robot: Testing breakage of this commit

| Package Name | master | Tagged |
|--|--|--|
| AmplNLReader |  |  |
| CaNNOLeS |  |  |
| CUTEst |  |  |
| QuadraticModels |  |  |
| NLPModelsIpopt |  |  |
| NLPModelsJuMP |  |  |
| SolverTools |  |  |

**Comment by dpo** [comment]
We ❤️ TestBreakage!

**Comment by abelsiqueira** [comment]
:robot: Testing breakage of this commit

| Package Name | master | Tagged |
|--|--|--|
| AmplNLReader |  |  |
| CaNNOLeS |  |  |
| CUTEst |  |  |
| QuadraticModels |  |  |
| NLPModelsIpopt |  |  |
| NLPModelsJuMP |  |  |
| SolverTools |  |  |

**Comment by abelsiqueira** [comment]
Rebased

**Comment by abelsiqueira** [comment]
:robot: Testing breakage of this commit

| Package Name | master | Tagged |
|--|--|--|
| AmplNLReader |  |  |
| CaNNOLeS |  |  |
| CUTEst |  |  |
| QuadraticModels |  |  |
| NLPModelsIpopt |  |  |
| NLPModelsJuMP |  |  |
| SolverTools |  |  |

**Comment by dpo** [comment]
I guess merging the other PR created conflicts here. would you mind rebasing again?

**Comment by abelsiqueira** [comment]
Rebased again.

**Comment by abelsiqueira** [comment]
:robot: Testing breakage of this commit

| Package Name | master | Tagged |
|--|--|--|
| AmplNLReader |  |  |
| CaNNOLeS |  |  |
| CUTEst |  |  |
| QuadraticModels |  |  |
| NLPModelsIpopt |  |  |
| NLPModelsJuMP |  |  |
| SolverTools |  |  |

**Comment by dpo** [comment]
This is breaking, so we'll have to limit the version of NLPModels in all dependents.

**Comment by dpo** [comment]
Thank you!

**Comment by abelsiqueira** [comment]
> This is breaking, so we'll have to limit the version of NLPModels in all dependents.

Yes, we have to start limiting versions by default.

**Pull request merged**
