### PR TITLE
Update requirements

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
Strange error due to ReverseDiffSparse: https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/166317505#L338

**Comment by dpo** [comment]
All the rest is green. Have you ever seen that error before? Rebuilding didn't help.

**Comment by abelsiqueira** [comment]
I restarted again and it worked. I think it wasn't RDS, but some dependency.

**Comment by abelsiqueira** [comment]
Thanks

**Comment by dpo** [comment]
Thank you.

**Pull request merged**
