### PR TITLE
Small fix and test

### PR DESCRIPTION
**Pull request by abelsiqueira**
Small fix on `hess_coord` of general `NLSModels`.
Add more tests to `LLSModel`.

### CODE REVIEW

**Comment by abelsiqueira** [comment]
Needs #115

**Comment by abelsiqueira** [comment]
I've collected a few things in this PR, let me know if you prefer separated

**Comment by dpo** [comment]
Small self-contained PRs really help. Also it would be great if you could describe the purpose of a PR when opening it. We should probably have issue and PR templates.

**Comment by abelsiqueira** [comment]
This is being separated in different PRs.

**Pull request closed without merging**
