### PR TITLE
Test mem argument of QN models

### PR DESCRIPTION
**Pull request by abelsiqueira**

### CODE REVIEW

**Comment by dpo** [comment]
Needs a new release of LinearOperators.

**Comment by abelsiqueira** [comment]
Updated.

**Comment by abelsiqueira** [comment]
:robot: Testing breakage of this pull request

| Package Name | master | stable |
|--|--|--|
| AmplNLReader | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/674559751) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/674559752) | 
| CUTEst | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/674559753) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/674559754) | 
| CaNNOLeS | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/674559755) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/674559756) | 
| NLPModelsIpopt | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/674559757) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/674559758) | 
| NLPModelsJuMP | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/674559759) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/674559760) | 
| QuadraticModels | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/674559761) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/674559762) | 
| SolverTools | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/674559763) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/674559764) |

**Comment by dpo** [comment]
Thank you.

**Pull request merged**
