### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by abelsiqueira**

### CODE REVIEW

**Comment by abelsiqueira** [comment]
:robot: Testing breakage of this pull request

| Package Name | master | stable |
|--|--|--|
| AmplNLReader | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653238298) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653238299) | 
| CUTEst | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653238300) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653238301) | 
| CaNNOLeS | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653238302) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653238303) | 
| NLPModelsIpopt | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653238304) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653238305) | 
| NLPModelsJuMP | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653238306) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653238307) | 
| QuadraticModels | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653238308) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653238309) | 
| SolverTools | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653238310) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653238311) |

**Comment by abelsiqueira** [comment]
:robot: Testing breakage of this pull request

| Package Name | master | stable |
|--|--|--|
| AmplNLReader | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653257283) | [-Fail-red)](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653257284) | 
| CUTEst | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653257285) | [-Fail-red)](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653257286) | 
| CaNNOLeS | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653257287) | [-Fail-red)](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653257288) | 
| NLPModelsIpopt | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653257289) | [-Fail-red)](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653257290) | 
| NLPModelsJuMP | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653257291) | [-Fail-red)](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653257292) | 
| QuadraticModels | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653257293) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653257294) | 
| SolverTools | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653257295) | [-Fail-red)](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653257296) |

**Comment by abelsiqueira** [comment]
:robot: Testing breakage of this pull request

| Package Name | master | stable |
|--|--|--|
| AmplNLReader | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653416623) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653416627) | 
| CUTEst | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653416629) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653416630) | 
| CaNNOLeS | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653416631) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653416632) | 
| NLPModelsIpopt | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653416633) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653416634) | 
| NLPModelsJuMP | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653416635) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653416636) | 
| QuadraticModels | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653416637) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653416638) | 
| SolverTools | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653416639) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653416640) |

**Comment by dpo** [comment]
Thank you.

**Pull request merged**
