### PR TITLE
Change LLSModel to use coordinate format internally

### PR DESCRIPTION
**Pull request by abelsiqueira**

### CODE REVIEW

**Comment by abelsiqueira** [comment]
:robot: Testing breakage of this pull request

| Package Name | master | stable |
|--|--|--|
| AmplNLReader | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/667027547) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/667027548) | 
| CUTEst | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/667027549) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/667027550) | 
| CaNNOLeS | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/667027551) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/667027552) | 
| NLPModelsIpopt | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/667027553) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/667027554) | 
| NLPModelsJuMP | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/667027555) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/667027556) | 
| QuadraticModels | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/667027557) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/667027558) | 
| SolverTools | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/667027559) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/667027560) |

**Comment by dpo** [comment]
Thanks, that looks great. Does that mean we'll need another type for LLS problems defined by linear operators?

**Comment by abelsiqueira** [comment]
Yes, I guess so.

**Comment by dpo** [comment]
Thank you.

**Pull request merged**
