### PR TITLE
Update docs to new Documenter

### PR DESCRIPTION
**Pull request by abelsiqueira**

### CODE REVIEW

**Comment by dpo** [comment]
Many thanks for all this! It looks good to me, though I don't know if I can see the docs generated somewhere before merging?!

**Comment by abelsiqueira** [comment]
Not by default, but I'll generate a manual version.

**Comment by abelsiqueira** [comment]
Here: http://abelsiqueira.github.io/NLPModels.jl/tmp/

**Comment by dpo** [comment]
Thank you!

**Pull request merged**
