### PR TITLE
add reset_data! to docs

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by abelsiqueira** [comment]
:robot: Testing breakage of this pull request

| Package Name | master | stable |
|--|--|--|
| AmplNLReader | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/668208425) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/668208426) | 
| CUTEst | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/668208427) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/668208428) | 
| CaNNOLeS | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/668208429) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/668208430) | 
| NLPModelsIpopt | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/668208431) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/668208432) | 
| NLPModelsJuMP | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/668208433) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/668208434) | 
| QuadraticModels | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/668208435) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/668208436) | 
| SolverTools | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/668208437) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/668208438) |

**Comment by dpo** [comment]
Still getting `Warning: 1 docstring potentially missing:`: https://travis-ci.org/github/JuliaSmoothOptimizers/NLPModels.jl/jobs/668208440#L299.

What's missing here?

**Comment by abelsiqueira** [comment]
If `reset_data!` is not exported, I think it needs `NLPModels.reset_data!`.

**Comment by abelsiqueira** [comment]
:robot: Testing breakage of this pull request

| Package Name | master | stable |
|--|--|--|
| AmplNLReader | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/668259186) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/668259187) | 
| CUTEst | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/668259188) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/668259189) | 
| CaNNOLeS | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/668259190) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/668259191) | 
| NLPModelsIpopt | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/668259192) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/668259193) | 
| NLPModelsJuMP | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/668259194) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/668259195) | 
| QuadraticModels | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/668259196) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/668259197) | 
| SolverTools | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/668259198) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/668259199) |

**Pull request merged**
