### PR TITLE
Release 1

### PR DESCRIPTION
**Pull request by abelsiqueira**
Anything to add before v1?

I'll use the breakage to see the situation with other packages as well.

### CODE REVIEW

**Comment by dpo** [comment]
The README needs a little love. Some images are broken and the name of NLPModelsJuMP is misspelled. There may be other things to improve there.

**Comment by abelsiqueira** [comment]
:robot: Testing breakage of this pull request

| Package Name | master | stable |
|--|--|--|
| AmplNLReader | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653175794) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653175795) | 
| CUTEst | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653175796) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653175797) | 
| CaNNOLeS | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653175798) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653175799) | 
| NLPModelsIpopt | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653175800) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653175801) | 
| NLPModelsJuMP | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653175802) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653175803) | 
| QuadraticModels | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653175804) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653175805) | 
| SolverTools | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653175806) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/653175807) |

**Comment by abelsiqueira** [comment]
Of course all breakage tests fail, because NLPModels version (1.0) is not supported. :disappointed: 
I'm gonna work on README and check the breakage from there.

**Comment by abelsiqueira** [comment]
Closing in favor of opening again when all is done in #278

**Pull request closed without merging**
