### PR TITLE
Manually compute the derivates of Brownden

### PR DESCRIPTION
**Pull request by abelsiqueira**

### CODE REVIEW

**Comment by dpo** [comment]
You were not using Julia 1.2. Would you mind rebasing?

**Comment by dpo** [comment]
Let's just be optimistic.

**Comment by abelsiqueira** [comment]
Thanks for merging.

**Comment by dpo** [comment]
Do we need a new release for this to take effect in other repositories?

**Comment by abelsiqueira** [comment]
Yes, and update the minimum version of AmplNLReader

**Pull request merged**
