### PR TITLE
Check return values of the inplace functions

### PR DESCRIPTION
**Pull request by abelsiqueira**
Has some conflicts with #69

### CODE REVIEW

**Comment by dpo** [comment]
And conflicts here.

**Comment by abelsiqueira** [comment]
Rebased

**Comment by dpo** [comment]
`invalid subtyping in definition of JuMPArray`: https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/194195896#L4334 ???

**Comment by abelsiqueira** [comment]
Same here: https://github.com/JuliaSmoothOptimizers/CUTEst.jl/pull/108#issuecomment-274343701

**Pull request merged**
