### PR TITLE
More multiple precision fixes

### PR DESCRIPTION
**Pull request by abelsiqueira**
Fix missing `eltype(vals)` in #245 and other related multiple precision errors.

### CODE REVIEW

**Comment by abelsiqueira** [comment]
:robot: Testing breakage of this pull request

| Package Name | master | stable |
|--|--|--|
| AmplNLReader | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/656537745) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/656537746) | 
| CUTEst | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/656537747) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/656537748) | 
| CaNNOLeS | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/656537749) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/656537750) | 
| NLPModelsIpopt | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/656537751) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/656537752) | 
| NLPModelsJuMP | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/656537753) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/656537754) | 
| QuadraticModels | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/656537755) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/656537756) | 
| SolverTools | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/656537757) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/656537758) |

**Comment by abelsiqueira** [comment]
I made another mistake in this, which the tests don't check.

**Comment by abelsiqueira** [comment]
:robot: Testing breakage of this pull request

| Package Name | master | stable |
|--|--|--|
| AmplNLReader | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/656736428) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/656736429) | 
| CUTEst | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/656736430) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/656736431) | 
| CaNNOLeS | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/656736432) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/656736433) | 
| NLPModelsIpopt | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/656736434) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/656736435) | 
| NLPModelsJuMP | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/656736436) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/656736437) | 
| QuadraticModels | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/656736438) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/656736439) | 
| SolverTools | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/656736440) | [](https://travis-ci.org/JuliaSmoothOptimizers/NLPModels.jl/jobs/656736441) |

**Comment by abelsiqueira** [comment]
Fixed

**Comment by dpo** [comment]
Thank you.

**Pull request merged**
