### PR TITLE
[skip ci] Test probot

### PR DESCRIPTION
**Pull request by abelsiqueira**
@dpo Approve this, please.

### CODE REVIEW

**Comment by abelsiqueira** [comment]
Took some time, but it worked.

**Comment by dpo** [comment]
Did it merge automatically? That's awesome!!!

**Comment by abelsiqueira** [comment]
Thanks, @bobvanderlinden for the package and helping update for our use case.

**Comment by bobvanderlinden** [comment]
Glad to see the change is already of value. Thanks for your contributions!

**Pull request merged**
