### PR TITLE
Improve hessian tests

### PR DESCRIPTION
**Pull request by tmigot**
Add hessian functions in test problems, so that we can also test consistency for `hprod` of nls problems.

### CODE REVIEW

**Comment by tmigot** [comment]
Test failed because of PR #318

**Comment by tmigot** [comment]
The diff still thinks that the modifications in `src/feasibility_residual.jl` are new, but they were already merged in PR #318.

**Comment by abelsiqueira** [comment]
> The diff still thinks that the modifications in `src/feasibility_residual.jl` are new, but they were already merged in PR #318.

That's because you haven't rebased your branch on top of the updated `master`. See here: https://github.com/tmigot/NLPModels.jl/network

Looking at your graph, I recommend
- git checkout master # Go to your master branch
- git branch tmp # Create a backup of that branch
- git reset --hard jso/master # Reset your master to jso master (jso is our JSO remote)
- git rebase master imp_hess_tests # rebase

As a rule of thumb, your master should never be ahead of JSO's.

**Comment by abelsiqueira** [comment]
PS. These git commands can destroy your work, backup if you're not sure.

**Comment by tmigot** [comment]
> PS. These git commands can destroy your work, backup if you're not sure.

Thanks for your help! It looks alright now.

**Review by abelsiqueira — APPROVED** [review]
I was a little worried about the addition of `hess_structure` and `_coord` functions for NLS because we are not implementing it and we are not expecting them to be implemented. I'm not sure if adding these functions is a bad thing, though, so I am approving and leaving the decision of whether to keep them as well to @dpo.

**Comment by dpo** [comment]
We’ve had requests for hess, hess_structure & co. for LLS problems. It’s a bad idea to use them but I guess we could allow the user to implement and test them.

**Comment by dpo** [comment]
Thank you

**Pull request merged**
