### PR TITLE
generic MPB interface

### LINKED ISSUE #38: MathProgBase wrapper
Create a MPB wrapper. Possibly supersedes JuMPNLPModel

### PR DESCRIPTION
**Pull request by dpo**
Closes #38.

@mlubin

### CODE REVIEW

**Comment by dpo** [comment]
Wait for #46.

**Comment by mlubin** [comment]
Does this supersede AMPLMathProgInterface?

**Comment by mlubin** [comment]
Given that there are links from AMLP to NLP model

**Comment by dpo** [comment]
Yes. I [reused your code](https://github.com/JuliaSmoothOptimizers/NLPModels.jl/blob/430b521a812da11633c85149661a9ea7f16c0f0a/src/nlp_to_mpb.jl#L3). Let me know if the acknowledgement is appropriate. If you'd rather submit a PR with your name on it, I'm very happy to do that too.

The main idea is that modeling languages such as AMPL or CUTEst need only specify what features are available, e.g., https://github.com/JuliaSmoothOptimizers/AmplNLReader.jl/blob/f3bf51c84da2ead78acf7b5f6b2655da7f17092b/src/mpb_interface.jl#L5.

**Comment by mlubin** [comment]
Yes, the acknowledgement is appropriate. Thanks!

**Comment by abelsiqueira** [comment]
Thanks

**Pull request merged**
